version: '3'
services:
    api:
        container_name: api-albums-dock
        restart: always
        build: .
        ports:
            - 4000:8080
        links:
            - mongo
    mongo:
        container_name: mongoDB
        image: mongo
        ports:
            - 27022:27017